import { PublicKey } from '@solana/web3.js'
import type { PoolConfig, VirtualPool } from './types'
import { BN } from 'bn.js'

export const DEFAULT_POOL_CONFIG: PoolConfig = {
  migrationQuoteThreshold: new BN(0),
  collectFeeMode: 0,
  curve: [],
  activationType: 0,
  partnerLockedLpPercentage: 0,
  partnerLpPercentage: 0,
  creatorLockedLpPercentage: 0,
  creatorLpPercentage: 0,
  migrationSqrtPrice: new BN(0),
  padding0: [],
  padding1: [],
  feeClaimer: PublicKey.default,
  quoteMint: PublicKey.default,
  owner: PublicKey.default,
  poolFees: {
    baseFee: {
      cliffFeeNumerator: new BN(0),
      periodFrequency: new BN(0),
      reductionFactor: new BN(0),
      numberOfPeriod: 0,
      feeSchedulerMode: 0,
      padding0: [],
    },
    dynamicFee: {
      initialized: 0,
      padding: [],
      maxVolatilityAccumulator: 0,
      variableFeeControl: 0,
      binStep: 0,
      filterPeriod: 0,
      decayPeriod: 0,
      reductionFactor: 0,
      padding2: [],
      binStepU128: new BN(0),
    },
    padding0: [],
    padding1: [],
    protocolFeePercent: 0,
    referralFeePercent: 0,
  },
  migrationOption: 0,
  tokenDecimal: 0,
  tokenType: 0,
  swapBaseAmount: new BN(0),
  migrationBaseThreshold: new BN(0),
  sqrtStartPrice: new BN(0),
  quoteTokenFlag: 0,
  version: 0,
  padding2: [],
}

export const DEFAULT_VIRTUAL_POOL: VirtualPool = {
  volatilityTracker: {
    lastUpdateTimestamp: new BN(0),
    padding: [],
    sqrtPriceReference: new BN(0),
    volatilityAccumulator: new BN(0),
    volatilityReference: new BN(0),
  },
  baseReserve: new BN(0),
  quoteReserve: new BN(0),
  sqrtPrice: new BN(0),
  config: PublicKey.default,
  creator: PublicKey.default,
  baseMint: PublicKey.default,
  baseVault: PublicKey.default,
  quoteVault: PublicKey.default,
  protocolBaseFee: new BN(0),
  protocolQuoteFee: new BN(0),
  tradingBaseFee: new BN(0),
  tradingQuoteFee: new BN(0),
  activationPoint: new BN(0),
  isMigrated: 0,
  isPartnerWithdrawSurplus: 0,
  isProcotolWithdrawSurplus: 0,
  metrics: {
    totalProtocolBaseFee: new BN(0),
    totalProtocolQuoteFee: new BN(0),
    totalTradingBaseFee: new BN(0),
    totalTradingQuoteFee: new BN(0),
  },
  poolType: 0,
  padding0: [],
  padding1: [],
}
